// <auto-generated />
namespace WebsiteForms.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class HabeasData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HabeasData));
        
        string IMigrationMetadata.Id
        {
            get { return "202211081725266_HabeasData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
